Update latex-to-pdf.yml

diff --git a/.github/workflows/latex-to-pdf.yml b/.github/workflows/latex-to-pdf.yml
--- a/.github/workflows/latex-to-pdf.yml
+++ b/.github/workflows/latex-to-pdf.yml
@@ -30,33 +30,36 @@ jobs:
         run: |
           sudo apt-get install -y inkscape
 
-      # Find the latest modified folder in src/2 - RTB, excluding PDF, images, and contents directories
+      # Trova la cartella più recente
       - name: Find latest folder
         id: find_latest_folder
         run: |
           latest_folder=$(find "src/2 - RTB" -type d -not -path "*/PDF/*" -not -path "*/images/*" -not -path "*/contents/*" -exec stat --format='%Y-%m-%d %H:%M:%S %n' {} \; | sort -nr | head -n 1 | awk '{print $2}')
-
-          
-          # Check if the latest folder is within the 'images' or 'contents' directories, and if so, use the parent folder
+      
+          # Controlla se la cartella trovata è dentro 'images' o 'contents', in tal caso, scende di una cartella
           if [[ "$latest_folder" == *"/images"* ]] || [[ "$latest_folder" == *"/contents"* ]]; then
             echo "The latest modification is inside 'images' or 'contents'. Using the parent folder instead."
             latest_folder=$(dirname "$latest_folder")
           fi
-          
-          # If no folder was found, stop the process
+
+          # Se non è stata trovata nessuna cartella valida, fermati
           if [ -z "$latest_folder" ]; then
             echo "Error: No valid folder found in src/2 - RTB"
             exit 1
           fi
-          
+
           echo "Latest folder: $latest_folder"
           echo "LATEST_FOLDER=$latest_folder" >> $GITHUB_ENV
 
-      # Find the main .tex file in the latest folder, excluding images and contents directories
+      # Trova il file .tex principale nella cartella più recente
       - name: Find main .tex file
         id: find_tex
         run: |
-          # Cerca il file .tex principale nella cartella più recente
+          if [ -z "${{ env.LATEST_FOLDER }}" ]; then
+            echo "Error: LATEST_FOLDER is empty"
+            exit 1
+          fi
+
           main_tex=$(find "${{ env.LATEST_FOLDER }}" -type f -not -path "*/images/*" -not -path "*/contents/*" -name "*.tex" | sort -nr | head -n 1)
           
           if [ -z "$main_tex" ]; then
@@ -66,6 +69,7 @@ jobs:
           
           echo "Main TeX file: $main_tex"
           echo "MAIN_TEX=$main_tex" >> $GITHUB_ENV
+
 
       # Convert SVG to PDF
       - name: Convert SVG to PDF
